//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsHeartRateMonitor.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObsHeartRateMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to var elem = document.getElementById(&quot;heart-rate-value&quot;);
        ///var body = document.querySelector(&quot;body&quot;);
        ///
        ///function _clear() {
        ///	elem.innerText = &quot;?&quot;;
        ///	body.setAttribute(&quot;data-invalid&quot;, &quot;invalid&quot;);
        ///}
        ///
        ///function on_response() {
        ///	var data = this.responseText;
        ///	try {
        ///		data = JSON.parse(data);
        ///	} catch (e) {
        ///		// Ignore exception, try again
        ///		console.log(&quot;Error parsing JSON&quot;, e);
        ///		_clear();
        ///		return;
        ///	}
        ///	elem.innerText = data.value;
        ///	body.removeAttribute(&quot;data-invalid&quot;);
        ///}
        ///
        ///function on_error() {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlClientJs {
            get {
                return ResourceManager.GetString("HtmlClientJs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            font-size: 64pt;
        ///        }
        ///        body[data-invalid] {
        ///            display: none;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body data-url=&quot;%heart_rate_url%&quot;&gt;
        ///    &lt;div id=&quot;heart-rate-info&quot;&gt;&amp;#10084; %heart_rate_value%&lt;/div&gt;
        ///    &lt;script type=&quot;application/javascript&quot; src=&quot;client.js&quot;&gt;&lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HtmlTemplate {
            get {
                return ResourceManager.GetString("HtmlTemplate", resourceCulture);
            }
        }
    }
}
